--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	05/09/22 20:49:44 
--  Relational Database:       	E705D4A0 
--  Standards Option:          	Db2 for i 
CREATE FUNCTION TRUTHOBJ/@DATE ( 
	INDATE NUMERIC(6, 0) ) 
	RETURNS DATE   
	LANGUAGE RPGLE 
	SPECIFIC TRUTHOBJ/@DATE1 
	NOT DETERMINISTIC 
	NO SQL 
	CALLED ON NULL INPUT 
	NOT FENCED 
	EXTERNAL NAME 'TRUTHOBJ/DATECHEAT(@DATE)' 
	PARAMETER STYLE GENERAL ; 
  
COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/@DATE1 
( INDATE IS 'Numeric Date' ) ; 
  
LABEL ON SPECIFIC FUNCTION TRUTHOBJ/@DATE1 
	IS 'Date Cheat' ; 
  
  
CREATE FUNCTION TRUTHOBJ/@DATE ( ) 
	RETURNS DATE   
	LANGUAGE RPGLE 
	SPECIFIC TRUTHOBJ/@DATE0 
	NOT DETERMINISTIC 
	NO SQL 
	CALLED ON NULL INPUT 
	NOT FENCED 
	EXTERNAL NAME 'TRUTHOBJ/DATECHEAT(@DATE)' 
	PARAMETER STYLE GENERAL ; 
  
LABEL ON SPECIFIC FUNCTION TRUTHOBJ/@DATE0 
	IS 'Date Cheat' ; 
  
  
CREATE FUNCTION TRUTHOBJ/@DATE ( 
	INDATE NUMERIC(6, 0) , 
	INFORMAT CHAR(4) ) 
	RETURNS DATE   
	LANGUAGE RPGLE 
	SPECIFIC TRUTHOBJ/@DATE 
	NOT DETERMINISTIC 
	NO SQL 
	CALLED ON NULL INPUT 
	NOT FENCED 
	EXTERNAL NAME 'TRUTHOBJ/DATECHEAT(@DATE)' 
	PARAMETER STYLE GENERAL ; 
  
COMMENT ON PARAMETER SPECIFIC FUNCTION TRUTHOBJ/@DATE 
( INDATE IS 'Numeric Date' , 
	INFORMAT IS 'Numeric Date Format' ) ; 
  
LABEL ON SPECIFIC FUNCTION TRUTHOBJ/@DATE 
	IS 'Date Cheat' ; 
  
